// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_auY6NLjx6HJRhCspSUOTC06iEJyW8ik',
    appId: '1:1045367266634:web:96052b6a95025df47135b3',
    messagingSenderId: '1045367266634',
    projectId: 'educare-a7ea2',
    authDomain: 'educare-a7ea2.firebaseapp.com',
    storageBucket: 'educare-a7ea2.appspot.com',
    measurementId: 'G-NLN80CZW1D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDojQjICrcoNH6j1hPC2r4eaMP1YLMBHIs',
    appId: '1:1045367266634:android:7269f827a357dcf37135b3',
    messagingSenderId: '1045367266634',
    projectId: 'educare-a7ea2',
    storageBucket: 'educare-a7ea2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBloP0RZhX2ulWl9bARlLRh_tq3bWvmrqc',
    appId: '1:1045367266634:ios:b80bdd13ff1c14f67135b3',
    messagingSenderId: '1045367266634',
    projectId: 'educare-a7ea2',
    storageBucket: 'educare-a7ea2.appspot.com',
    iosClientId: '1045367266634-lsr120206v5fq3piubv3qi57ne223igp.apps.googleusercontent.com',
    iosBundleId: 'com.example.guailet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBloP0RZhX2ulWl9bARlLRh_tq3bWvmrqc',
    appId: '1:1045367266634:ios:b80bdd13ff1c14f67135b3',
    messagingSenderId: '1045367266634',
    projectId: 'educare-a7ea2',
    storageBucket: 'educare-a7ea2.appspot.com',
    iosClientId: '1045367266634-lsr120206v5fq3piubv3qi57ne223igp.apps.googleusercontent.com',
    iosBundleId: 'com.example.guailet',
  );
}
